### ISSUE TITLE
Error "SQLSTATE[HY000] [2002] Connection refused" in third step 

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#11]
**Problem**:  I am getting error "SQLSTATE[HY000] [2002] Connection refused" in third step "Database backup" after succesfull completion of second step. 

Steps to reproduce

Step 2 "Database analysis" completes correctly https://dev-fibonacci-backdrop.pantheonsite.io/d2b-migrate/analysis 
after download of  module click on blue button at the bottom "Next step: Backup Database"

**Additional information**

1- here is error from log:
https://dev-fibonacci-backdrop.pantheonsite.io/admin_bar/flush-cache?token=kasdadfadfdasfdfuaciKJbDKsfTC5q-k9ttVEKr4npmHI

https://dev-fibonacci-backdrop.pantheonsite.io/js/admin_bar/cache/3bb4asdfadfadsfasfsafads61b6b1bb92841

`PDOException: SQLSTATE[HY000] [2002] Connection refused in backup_migrate_source_db->_get_db_connection() (line 235 of /code/modules/backup_migrate/includes/sources.db.inc).`

2- I get same error when I go to main page in backup and upgrade module 
https://dev-fibonacci-backdrop.pantheonsite.io/admin/config/system/backup_migrate
I can access other pages in backup and migrate from admin menu, like restore page https://dev-fibonacci-backdrop.pantheonsite.io/admin/config/system/backup_migrate/restore

**Comment by herbdool** [comment]
I can't replicate the error so would need more details. Locally I did this by having two databases where the site could connect to both the Drupal 7 and the Backdrop. How are you able to connect to both databases on Pantheon?

Also, this seems to be more an error with backup_migrate module rather than this one.

**Comment by irinaz** [comment]
@herbdool , it seems that this error has been fixed already, thank you!  Now I have trouble in the Database Backup step, I will close this issue and open another one.
