### ISSUE TITLE
How to test this module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/d2b_migrate#2]
We may have folks at our upcoming sprint that are interested in helping to test this module, but lack availability of a Drupal 7 database to start testing with. What advice might we provide for how to properly test a d2b migrate module. 

Instructions suggest that testing this involves having an existing Drupal 7 site and a new Backdrop CMS site on the same server. 

If one were to test this using two lando sites (one Drupal and one BackdropCMS) on their local computer, would this work? Are there any tricks to making this work?

Would it help if we had a clean Drupal 7 database available for testing?
https://docs.google.com/document/d/1GruXFHmdSVj7H_mGZdUQGrZQDsPVIPMRlhuuyITOT7Y/edit#

**Comment by docwilmot** [comment]
Well actually, the D7 site is untouched, so you just need that once. To test, what you need is a clean Backdrop site, each time, into which you import the data from the D7 site. So a way to build a new default Backdrop site as fast as possible is the key to testing.

**Comment by irinaz** [comment]
Spin new site on Pantheon https://dashboard.pantheon.io/sites/create?upstream_id=bf703821-4c18-45a1-88b8-3d9ec302273d is best way to test.   Readme file has very good instructions.

**Comment by irinaz** [comment]
@stpaultim , we updated Read.me file, can we close this ticket?  It seems that this ticket was related specifically for a sprint.
