### ISSUE TITLE
Streamline existing workflow steps

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/d2b_migrate#21]
As an alternative to https://github.com/backdrop-contrib/d2b_migrate/issues/16, which would require moving the import to the first step, we might want to keep the current workflow step order, but streamline the existing steps.

Here are the current steps:

1. Start
2. Source database
3. Database analysis
4. Database backup
5. Backup files
6. Migrate database

The idea here is that we keep using a set of database credentials. Steps 1 - 3 stays the same.

Step 4 we would change to not require the user to download the database backup file, instead we would directly save it to disk.

Step 5 stays the same (or is out of scope for this issue).

Step 6 we remove the option to upload a file and the option to select a specific backup. Instead we always use the backup created in step 4.

This would eliminate two of the more confusing steps. As a first-time user I was really thrown off where the database backup should be saved in step 3.

**Comment by docwilmot** [comment]
Pushed some changes to help navigation.

**Comment by irinaz** [comment]
I would love to see an option to upload db in addition to connecting to the host. 

<img width="880" alt="new source screen" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/9542781f-50b1-42a5-9df5-52e02ea4d7e2">. 

@docwilmot , thank you so much for adding configuration that shows that db is already connected, now we can see what is status for db connection in both states 
<img width="1173" alt="d2b-database connected" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/66ea1c15-336a-4163-91ae-03856e8e875d">

It looks like db connection times out after 8(?)hours, but at the same time we have already copy of source db in manual downloads directory we might reuse this db if we can resolve #16

**Comment by docwilmot** [comment]
This is as streamlined as we can get I think. Closing.
