### ISSUE TITLE
File copy failed

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/d2b_migrate#23]
Seems like the file copy failed entirely (in my case), so on PHP 8.2 I get a bunch of nagging.

```
Warning: filesize(): stat failed for public://styles/cat-2464780_960_720.jpg
Warning: filesize(): stat failed for public://2022-10/191432453-04f33bb4-b12f-45d4-b11c-0d94f34f6acc.png
```
Maybe better fail gracefully (single files may actually be gone already on D7)?

But my suspicion is, that something's wrong with the file copy process, anyway.

Looking at the paths above - both are correct, but no image got copied.

Another possible problem: file directories got created properly, but in `/files`, which means that if some of the files are used inline (via editor), they'll end up as 404, as the URL changes.

**Comment by indigoxela** [comment]
Nobody's concerned? :stuck_out_tongue_winking_eye:

**Comment by docwilmot** [comment]
The copy files functionality doesnt seem like a very solid idea to me generally to be honest, so I havent been paying much attention to this I admit. Also considered getting rid of it. Wonder if @irinaz thinks its a useful thing to keep?

**Comment by irinaz** [comment]
This step would be VERY useful to be able to upload files archive in exactly same way as we do in Backup and Migrate now.   Getting files one by one does not seem to be a good option.  Also some sites have private files which cannot be accessed via url without authentication. 
<img width="595" alt="Screenshot 2023-12-03 at 7 14 25 PM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/e40452bf-0071-4b14-9ea6-eeb2f0817437">

**Comment by indigoxela** [comment]
> Also considered getting rid of it.

I think, file handling is a crucial step.

Whether uploading a tar, getting them one by one, or instructing where to put them. The conversion to File entities is important to make this module really helpful. Skipping that doesn't seem like a good option, as then this module is less helpful than the currently available upgrade path.

**Comment by docwilmot** [comment]
Comments seem to suggest this is fixed.
