### ISSUE TITLE
Step "Download Available projects" breaks if there is Google Analytics module

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#27]
I am migrating site that has disabled "Google Analytics" module and download stops with the following error message. 
@quicksketch , you mentioned during sprint on Nov 18 that there is something specific about this module - can you share your insights?  Thank you in advance!

`Notice: Undefined index: google_analytics in d2b_migrate_analysis_download_projects() (line 388 of /Users/irinazaks/Sites/localhost/backdroppress/modules/d2b_migrate/d2b_migrate.module).`

**Comment by docwilmot** [comment]
It seems the D8 module is called `google_analytics` while the Backdrop version is `googleanalytics` (the D7 version was also `googleanalytics`) so the function is looking for the wrong name.

**Comment by irinaz** [comment]
@docwilmot , thank you so much!  If we are to fix this bug, what approach would you suggest?

**Comment by docwilmot** [comment]
Untested, try add before **line 387**:
```
if ($project_name == 'google_analytics`) {
  $project_name = 'googleanalytics';
}
```

**Comment by docwilmot** [comment]
This should be fixed. Projects with wrong name will need to be manually downloaded

**Comment by irinaz** [comment]
https://github.com/backdrop-contrib/d2b_migrate/issues/30 is solution to this issue
