### ISSUE TITLE
Create New Destination for D2B - high priority

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#28]
On installation of d2b module create new destination for storing D7 source website data  /admin/config/system/backup_migrate/settings/destination/add

**Comment by docwilmot** [comment]
@irinaz why do we need a new destination?

**Comment by irinaz** [comment]
My ideal (hopefully in the near future) scenario is that we can have two choices - file upload or connecting to host https://github.com/backdrop-contrib/d2b_migrate/issues/16. 

It would be great to store "source" D7 db in a directory that is different from backup-and-migrate directory  to clearly indicate difference between new DB backups and "pre-migration" db. 

<img width="880" alt="new source screen" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/eb499933-4df7-4d28-866b-afe1092e123b">

With the current design it is easy to confuse files in backup-and-migrate directory

<img width="1186" alt="two-destinations" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/91782e9c-bdce-4b36-bea3-6c1c426565c4">

**Comment by irinaz** [comment]
This feature is not needed anymore with new UI and flow.
