### ISSUE TITLE
Indicate that connection to D7 db is set - high priority

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#29]
On page /d2b-migrate/source indicate that db connection is already set.   Currently this information is available within backup and migrate module  /admin/config/system/backup_migrate/settings/source 

similar to this 

 
<img width="880" alt="new source screen with db connection" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/9a508102-0104-4c6f-ad71-50a7ba558cf8">

**Comment by docwilmot** [comment]
Done

**Comment by docwilmot** [comment]
Is this OK to close?

**Comment by irinaz** [comment]
This issues has been tested and is ready for release
