### ISSUE TITLE
Add option to select projects for download in step /d2b-migrate/analysis - high priority

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#30]
Some sites have too many modules to download in  step /d2b-migrate/analysis , and also some modules have different name in BD, like Google Analytics.  Please add checkboxes similar to /admin/config/system/updates that allow a user to select which modules to download and install. 
<img width="611" alt="Screenshot 2023-11-21 at 12 56 39 PM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/c1acd3ee-b087-4c7e-9dbd-38c564ec9d92">

**Comment by docwilmot** [comment]
Done

**Comment by irinaz** [comment]
Thank you, this looks great.  I have noticed that all projects that cannot be downloaded have the same  greyed out chechbox marked as selected.   How difficult is it to make boxes for projects that have status Not ported/Download from Github greyed out without white "check" mark?  It is confusing for a user to see that module has "checked" mark in the same way in two different scenarios

-  module is already downloaded or in core 
- module is not ported or does not have a release.

NOW
<img width="835" alt="Screenshot 2023-11-26 at 7 17 02 PM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/431198a0-927e-4b81-822a-938fe769660c">

WISHLIST
<img width="762" alt="Screenshot 2023-11-26 at 7 23 51 PM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/f6053f59-704a-4360-b8c8-28ca58ddd1ee">

**Comment by docwilmot** [comment]
Meant to do that actually, done now. Projects not ported and those on GitHub are now unchecked. Because those are two categories not on disc yet.

**Comment by quicksketch** [comment]
Thanks this looks awesome!

**Comment by irinaz** [comment]
@quicksketch , @docwilmot , I think that based on comments we can close this issue.  Thank you so much for making it work so quickly!
