### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/d2b_migrate#31]
Is this the correct way to report any issues...? In my case, database import was abandoned... I had two languages defined (EN, DE)

Error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'langcode' in 'where clause': SELECT redirect.`rid` AS `rid` FROM {redirect} redirect WHERE (`source` LIKE :db_condition_placeholder_0 ESCAPE '\\') AND (`langcode` IN (:db_condition_placeholder_1, :db_condition_placeholder_2)) ; Array ( [:db_condition_placeholder_0] => admin/config/system/backup\_migrate/restore [:db_condition_placeholder_1] => en [:db_condition_placeholder_2] => und )

**Comment by docwilmot** [comment]
At what stage in the wizard was this? The final restore step? I dont think D2B calls uses path `admin/config/system/backup_migrate/restore`, so I'm not sure how this error would arise. Did you navigate to that path during using D2B?

**Comment by mazzech** [comment]
OK, I did not have a proper private path > start over, define path > going through the steps > final restore step throws a 503 error > manually entering start page URL (just the domain name;-) > get this message:

My Backdrop Site
Error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'langcode' in 'where clause': SELECT redirect.`rid` AS `rid` FROM {redirect} redirect WHERE ( (`source` LIKE :db_condition_placeholder_0 ESCAPE '\\') OR (`source` = :db_condition_placeholder_1) )AND (`langcode` IN (:db_condition_placeholder_2, :db_condition_placeholder_3)) ; Array ( [:db_condition_placeholder_0] => home [:db_condition_placeholder_1] => [:db_condition_placeholder_2] => en [:db_condition_placeholder_3] => und )

**Comment by docwilmot** [comment]
So, again, to be clear, you went through the entire wizard, all the steps, then clicked the final "Upgrade database" button, then got a 503? 

Then you typed the home page in the address bar and got the above error?

If after the 503 you instead type `DOMAIN_ADDRESS/core/update.php` does it reach the update process?

**Comment by mazzech** [comment]
I just removed the language EN on the source site (its german-only anyway, but initial installation had to be EN in D7 > tried again > this time "only" a timeout error:

Request Timeout
This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

**Comment by mazzech** [comment]
Yes, as you describe it... going to update.php also results in error connected with some language settings: 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'core/modules/language/language.module' for key 'PRIMARY': INSERT INTO {system} (`filename`, `name`, `type`, `status`, `bootstrap`, `schema_version`, `weight`, `info`) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5,

I have entity translation activated on the source site, I will try to remove it...

**Comment by irinaz** [comment]
@mazzech , can you test the following scenario

1. setup new clean backdrop site
2. use backup and upgrade restore function to import D7 database into the site
3. run /core/update.php 

If you see the same error then it is problem with the update process, not with d2b module.  We can ask core team where we should file issues for update process.

**Comment by mazzech** [comment]
Hi Irinaz, I did exactly this by mistake when I first tried out the module. Same message, yes. I suppose it's because of the entity translation in the source site, which assigns several languages to the same node ID. Thank you anyway for your efforts on the D7 migration project, I really appreciate it and will try with a monolingual project soon:-)

**Comment by irinaz** [comment]
@mazzech , can we close this issue if it not related to d2b?

**Comment by mazzech** [comment]
yes:-)

**Comment by irinaz** [comment]
thanks, closing
