### ISSUE TITLE
No Pending Updates - Fail (database upgrade not running)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/d2b_migrate#36]
Testing the latest dev branch of module. I was able to connect to the database of D7 site, identify and download modules. I manually moved files from D7 to Backdrop files directory. 

When I got here:
![image](https://github.com/backdrop-contrib/d2b_migrate/assets/3144571/cd8820fc-f835-4afe-a891-26a519177dc1)

I clicked "Continue" and just got a "No Pending Updates" message.
![image](https://github.com/backdrop-contrib/d2b_migrate/assets/3144571/999fa682-163c-413e-8a46-7b35069a2425)

In previous version of module, I was able to get past here to other problems.

**Comment by stpaultim** [comment]
I found these errors in log.
![image](https://github.com/backdrop-contrib/d2b_migrate/assets/3144571/81815b32-1d95-455a-9d13-a6f850d7193c)

**Comment by stpaultim** [comment]
This might be part of the problem:
![image](https://github.com/backdrop-contrib/d2b_migrate/assets/3144571/10201312-380b-4add-b1a5-2c3ca3333829)

I will test again with the latest tagged release.

**Comment by irinaz** [comment]
@stpaultim , I did testing on the site that does not have D2B and it seems like an issue in Backup_migrate module, not D2B.   I will try to test wiht previous version of Backdrop core.

**Comment by stpaultim** [comment]
@irinaz 

I tested again with the released version of the module and I got to the migration process and then had the kind of errors I would expect.

The 1.x-1.x branch doesn't even get me that far. It seems pretty clear that the problem is that it's not downloading the database as expected. So, maybe that is a problem with backup and migrate.

**Comment by stpaultim** [comment]
@irinaz and @docwilmot - I tried with the 1.x-1.x (dev) version of Backup and Migrate, because there are bug fixes that have not been released yet. 

Same results.

**Comment by stpaultim** [comment]
@irinaz Since you mentioned trying with an earlier version of Backup and Migrate, I did that as well. Also same results. 

I've tried with the .24, .25, and 1.x-1.x versions of Backup and Migrate all WITH the 1.x-1.x version of D2B. Always same results. I don't think I have the knowledge to be sure if the problem is Backup and Migrate or D2B and am not sure if I can open an issues other than this one, with the knowledge I have.

![image](https://github.com/backdrop-contrib/d2b_migrate/assets/3144571/4aa16671-e120-4894-8eb2-b97c12de558e)

**Comment by argiepiano** [comment]
There are a bunch of fixes in Backup and Migrate that will get released soon. Try using the dev branch of BM. 

Oops - just saw that you did that already.

**Comment by irinaz** [comment]
> There are a bunch of fixes in Backup and Migrate that will get released soon. Try using the dev branch of BM.
> 
> Oops - just saw that you did that already.

I will file issue in Backup and Migrate module related to the problem that we see, but not related to D2B module

**Comment by docwilmot** [comment]
Was a small oversight with file paths, should be fixed

**Comment by irinaz** [comment]
@docwilmot , thank you so much for working on this!!! I downloaded new code, checked that I have most recent version

I can successfully run upgrade when I connect to remote host.  

When I tried to upload db nothing happens,  and here is a message  that I see in log

`Warning: Undefined array key "type" in d2b_migrate_form_backup_migrate_crud_edit_form_alter() (line 286 of /Users/irinazaks/Sites/localhost/demo-backdroppress/modules/d2b_migrate-1.x-1.x/d2b_migrate.module).`

I tested uploading db using backup and migrate and see the same problem (reported by @stpaultim in https://github.com/backdrop-contrib/d2b_migrate/issues/37 )

**Comment by irinaz** [comment]
I think that we can create new release with a temporary message that DB upload has a bug that is in Backup and Migrate module https://github.com/backdrop-contrib/backup_migrate/issues/136.   D2B will work after https://github.com/backdrop-contrib/backup_migrate/issues/136 is fixed - @argiepiano , thank you for working on the issue!

**Comment by docwilmot** [comment]
This is strange. I've done at least 10 upgrades on my local with no problem while testing this. Plus the validate function for setting the source has several `form_set_error()` messages to catch failures, but youre getting no message at all like the validate function isn't being called? And the submit function should move you to the next step of the wizard, but the source form is just reloading, so the submit isnt being called either. I cannot imagine what could be causing this TBH. The `undefined type` notice is fixable (fixed), but I'm stumped. Is this on Pantheon?

**Comment by irinaz** [comment]
@docwilmot , I figured out what is the problem with this db import - I am on php8.1. I can run update on php7.2 without any issues.  I will add comment to https://github.com/backdrop-contrib/backup_migrate/issues/136

**Comment by stpaultim** [comment]
@docwilmot I tested the 1.x branch on the site I've been testing recently and it worked as expected. Thank you so much. 

Shall we close this issue?

@irinaz

**Comment by docwilmot** [comment]
> @docwilmot , I figured out what is the problem with this db import - I am on php8.1. I can run update on php7.2 without any issues. I will add comment to https://github.com/backdrop-contrib/backup_migrate/issues/136

Most of my testing was on 8.2 but tried 8.1 without any problems as well. I'm assuming there is something strange about your setup @irinaz. Any PHP log messages or watchdog messages?

**Comment by irinaz** [comment]
@docwilmot , it does seem that issues is with my setup as I am testing many local variations.  

@stpaultim , I think that we can close this issue and release new version. If there are other bugs users can report them in separate issues.

**Comment by stpaultim** [comment]
Sounds good.
