### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/d2b_migrate#37]
In my testing, I'm finding this message in log.

Notice: Undefined index: type in d2b_migrate_form_backup_migrate_crud_edit_form_alter() (line 286 of /app/modules/d2b_migrate/d2b_migrate.module).

**Comment by irinaz** [comment]
@argiepiano , I get exactly same error when I try to restore db from file that I am uploading 
<img width="736" alt="Screenshot 2024-01-06 at 6 33 06 PM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/c38469cb-85ba-4680-a08f-c4fd2957db2b">

I can successfully restore when I am using file that is stored in manual backups directory. 

 
<img width="1201" alt="Screenshot 2024-01-06 at 6 43 16 PM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/d06a6e3a-7738-4e82-abca-4afdc2298dee">

**Comment by irinaz** [comment]
This bug does not reproduce anymore.  I will close this issue, and we can re-open it if needed.
