### ISSUE TITLE
Review commits to create interim release

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#38]
Please create interim release with the following added features 

- admin menu item https://github.com/backdrop-contrib/d2b_migrate/commit/ce1f1794ce83ced45ca8bd470f15562cc79e8a9a
- add checkboxed on download project page  - maybe more than one commit https://github.com/backdrop-contrib/d2b_migrate/commit/910b1821b9803d4ae24b883dc6ae38cd6efbeaa1 
- indicate disabled at source https://github.com/backdrop-contrib/d2b_migrate/commit/da4d23e667effcc0c3e6c8df8941ee1206949055 

Currently D7 db import is not working, so we would like to create interim release with some new features for option to connect to host without using D7 db upload (new feature).

**Comment by stpaultim** [comment]
As @irinaz discussed here. I will try to cherry pick the commits that work and test them. So that we can request a release with those changes, while the larger issues are still being worked on.

**Comment by docwilmot** [comment]
The whole thing was broken, so dont think we could release. Now its fixed, needs a bit more testing, then we'll release again.

**Comment by irinaz** [comment]
Thank you @docwilmot , I guess we can close this issue as we do not need to work on cherry picking :)

**Comment by stpaultim** [comment]
@docwilmot THANKS. I'll be testing tonight when I finish with my current video project.

**Comment by docwilmot** [comment]
Thanks, so I'll wait till you can test before release.
