### ISSUE TITLE
Create new release with new UI flow

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#39]
@docwilmot , @quicksketch , it would be great to create new release with new flow that allows both host connection and db upload.  We see lots of interest in community as D7 EOL is getting closer.

**Comment by docwilmot** [comment]
I believe the latest release is already up to date.

**Comment by irinaz** [comment]
@docwilmot , thank you so much, I suspect that I missed "second" release - it looks great and works great!!
