### ISSUE TITLE
Ask for Port Number in Drupal 7 Database Form

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/d2b_migrate#4]
When testing this module, we tried running this on Pantheon environments, which use non-standard port numbers (as opposed to 3306). It would be great if this module asked for port numbers so it could connect to odd port numbers.

**Comment by quicksketch** [comment]
Looks like the database form is actually coming from Backup/Migrate, so this would depend on https://github.com/backdrop-contrib/backup_migrate/issues/78.

**Comment by jenlampton** [comment]
That issue in backup and migrate has been fixed. Closing.
