### ISSUE TITLE
Set admin theme to default backdrop theme

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#40]
One challenge for site editors that move from D7 to Backdrop using D2B UI is settings for admin theme.  If source D7 site has admin theme set to a custom theme after upgrade Backdrop will not have that theme and therefore, users cannot get into the site. 

I would like to brainstorm possible solutions for this challenge 
@keiserjb , thank you for reporting this issue in Zulip after Office hours.

**Comment by keiserjb** [comment]
The best path in the interim may be to advise site owners to set the admin theme to seven before upgrading.

**Comment by irinaz** [comment]
> The best path in the interim may be to advise site owners to set the admin theme to seven before upgrading.

That is good point, we probably want to provide move help text before upgrade.  The challenge is that sometimes changing theme on the live site might impact Content Editor's experience.

**Comment by docwilmot** [comment]
Should be fixed

**Comment by irinaz** [comment]
Tested, works great, thank you!

**Comment by stpaultim** [comment]
I've also tested this and it seems to be working. Also, I believe that this update is in the most recent release on BackdropCMS.org. 

I will close this issue, reopen if there is a reason to keep this open. 

@irinaz or @docwilmot
