### ISSUE TITLE
Installed module but cannot 

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#6]
Installed module successfully, UI is great, need to be able to value for the port.  Got to step 3  /d2b-migrate/analysis and then get blank screen and error in logs

`PDOException: SQLSTATE[HY000] [2002] No such file or directory in d2b_migrate_analysis_fetch_projects() (line 509 of /code/modules/d2b_migrate-main/d2b_migrate.module).`

<img width="1148" alt="Screen Shot 2022-10-07 at 2 46 01 PM" src="https://user-images.githubusercontent.com/2497005/194665364-4feb6ec2-aeb0-4bd4-b813-36ef0a136a29.png">

**Comment by stpaultim** [comment]
Is this a duplicate of: https://github.com/backdrop-contrib/d2b_migrate/issues/4

Which is really? https://github.com/backdrop-contrib/backup_migrate/issues/78

**Comment by irinaz** [comment]
closed as duplicate
