### ISSUE TITLE
Error when clicking Download Available Projects

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/d2b_migrate#7]
On clicking "Download Available Projects" I get this error message... 

Argument 1 passed to installer_browser_get_project_release_data() must be of the type array, null given, called in /home/sites/1b/7/79e5d41fd9/public_html/subdomains/backdrop/modules/d2b_migrate-main/d2b_migrate.module on line 380

Using PHP 7.2
Updated to PHP 7.4 - still the same
Tried PHP 8.1 - still the same

This is the table of modules etc...

![image](https://user-images.githubusercontent.com/1705388/198831153-bc6317dc-e8ec-4f14-84d9-bb543f96266b.png)

**Comment by docwilmot** [comment]
This suggests that some project data returned from BackdropCMS is NULL. Are you able to debug? Put a `dpm($projects)` just above `foreach ($projects as $project) {`?

**Comment by juanolalla** [comment]
I've seen a problem with google_analytics, which in Backdrop changed its name to googleanalytics, and that makes it be null. For the moment I've added a condition to avoid the null problem, and the installer works.

**Comment by irinaz** [comment]
@docwilmot , does that mean that we can close this issue or we need more testing?

**Comment by irinaz** [comment]
@docwilmot , @albanycomputers , do you still see this problem or it has been fixed and we can close this issue?

**Comment by albanycomputers** [comment]
I'll have another try when I get back from holiday... mid-October.

**Comment by irinaz** [comment]
This steps seems to be working, I will label this issue closed.  Please reopen if it does not work for you.
