### ISSUE TITLE
Configure button is not showing up on modules page

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#8]
Info file https://github.com/backdrop-contrib/d2b_migrate/blob/main/d2b_migrate.info has configuration code `configure = d2b-migrate/start`, but configuration button in not showing up on page /admin/modules/list

**Comment by klonos** [comment]
@irinaz maybe you have an older version of the module installed? This has been fixed with #3:

![image](https://user-images.githubusercontent.com/2423362/215278553-ea666b04-53a3-4e8d-8d5c-08f4f9132a56.png)

Can you please confirm and close this issue if fixed indeed? Thanks.

**Comment by irinaz** [comment]
@klonos , thank you, I will test most recent version :)!

**Comment by irinaz** [comment]
@klonos , I can see this button in the new install, thank you for doing extra testing!!  Closing this ticket
